services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebanx-bank-api-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ebanx-bank-api-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
